### ISSUE TITLE
Add Loop

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-profunctor#2]
Suggested:

``` purescript
class (Category a, Strong a) <= Loop a where
  loop :: forall b c d. a (Tuple b d) (Tuple c d) -> a b c
```

with laws (cribbed from https://hackage.haskell.org/package/base-4.7.0.2/docs/Control-Arrow.html#t:ArrowLoop):

``` purescript
loop (f <<< first h) = loop f <<< h
loop (f >>> first h) = loop f >>> h
```

.. and the rest which I haven't figured out yet (TODO).

**Comment by DavidHarrison** [comment]
Does ArrowLoop depend on Haskell's lazy evaluation? It seems that Halogen's `loop` relies on an initial state.

**Comment by garyb** [comment]
Does `Costrong` cover this? `unfirst` is `loop` anyway, but there's also `unsecond`.

**Comment by paf31** [comment]
I think it possibly does. I don't fully understand the intent of `Costrong` yet, so I'm not sure.
