### ISSUE TITLE
`wrapIso` is wrong

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-profunctor#25]
The `t -> a` is the wrong way around 🙈

**Comment by hdgarrood** [comment]
Do we consider fixing this to be a breaking change, and if so, should we do it together with the 0.12 updates?

**Comment by garyb** [comment]
Yeah, it's a breaking change, and yep, we should fix it then :)

**Comment by garyb** [comment]
Resolved in 0.12 branch.
